### ISSUE TITLE
nil value (field 'uses')

### ISSUE THREAD

**Issue by Andyauk** [Djpowell23/gb-cigarettes#1]
[script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')

**Comment by Andyauk** [comment]
> [script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')

when you open the pack  you get this error

**Comment by TheDevster** [comment]
> > [script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')
> 
> when you open the pack you get this error

Did you complete the changes for inventory/html/js/app.js and inventory/server/main.lua as instructed in the readme?

**Comment by Andyauk** [comment]
> > > [script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')
> > 
> > 
> > when you open the pack you get this error
> 
> Did you complete the changes for inventory/html/js/app.js and inventory/server/main.lua as instructed in the readme?

yes everything is 100%

**Comment by Djpowell23** [comment]
Let me know if it gets working, that snippet in js/app.js should be the missing piece

**Comment by Andyauk** [comment]
no still getting 

`[script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')`

**Comment by Djpowell23** [comment]
Interested if any others are having this issue, works in my test and live city, unless its associated with the not having correct "uses" from like a shop or something. Currently only works as intended with 20 cigs per pack when it is spawned in. Hoping to find a fix or someone finds it and pr's it

**Comment by ryz87** [comment]
i got same issues

[script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:32: attempt to perform arithmetic on a nil value (field 'uses')
