### ISSUE TITLE
Suggestion pls add cigar

### ISSUE THREAD

**Issue by TweakyGaming** [Djpowell23/gb-cigarettes#10]
Please add cigars and more brands.
Thx for you work

**Comment by Djpowell23** [comment]
Just added Cardiaque Cigarettes and updated README. 
Cigars pose a different challenge because there is no animation that I'm aware that has the ped smoking a cigar.

**Comment by Djpowell23** [comment]
Also added yukon cigarettes. Making all 3 of the gta-brand cigarettes that I'm aware of

**Comment by TweakyGaming** [comment]
Thx nice work

**Comment by TweakyGaming** [comment]
`SCRIPT ERROR: @gb-cigarettes/server/main.lua:44: attempt to perform arithmetic on a nil value (field 'uses')`

I get these error messages every now and then

**Comment by Djpowell23** [comment]
People have reported that adding that part to the shops config where they're sold will solve that issue, at the bottom of the readme. If you're using a different inventory, there were some suggestions in the discord thread on QBCore Discord that helped people
