### ISSUE TITLE
[QUESTION] - Where did you get animation "SmokeCig"?

### ISSUE THREAD

**Issue by TheDevster** [Djpowell23/gb-cigarettes#2]
I replaced this one in my config to fix the issue, I use dpemotes as comes per QB Core framework installation using txAdmin recipe.   That code does not have the SmokeCig animation, so just curious where you got yours from.

Thanks!

**Comment by Djpowell23** [comment]
hmm, as much as I'm aware, it's the native smoke emote. It's the same emote as if someone were to type /smoke. Honestly might not be an updated artifact you're on? because we also use dpemotes

**Comment by jhlawson3** [comment]
I'm having a similar issue doesn't use the smoke emote when using a cigarette, and I'm on latest recommended artifacts

**Comment by Djpowell23** [comment]
My apologies, I forgot to add a snippet in there to put in dpemotes. It's in the readme now. Stress relief amount can be changed in the math.random in there. Intended to be low

**Comment by jhlawson3** [comment]
added the snippet and still doesn't do smoking emote
![Capture](https://user-images.githubusercontent.com/87055633/156855860-78c2e40e-e4b9-4ee1-be55-2427169db232.PNG)
?

**Comment by jhlawson3** [comment]
![Capture](https://user-images.githubusercontent.com/87055633/156856975-f1cc12a0-2a9f-4735-b952-15a6e66e2d52.PNG)

**Comment by Kerizi** [comment]
![Capture](https://user-images.githubusercontent.com/87055633/156861563-da759f0b-e652-4898-b4c5-82bc045af7e7.PNG)
