### ISSUE TITLE
arithmetic on a nil value (field 'uses')

### ISSUE THREAD

**Issue by tsoulii** [Djpowell23/gb-cigarettes#4]
Hi . The same thing happens with me and the cigarettes never end

[script:qb-cigarettes] SCRIPT ERROR: @qb-cigarettes/server/main.lua:28: attempt to perform arithmetic on a nil value (field 'uses')

![test1](https://user-images.githubusercontent.com/34017026/156908260-b61e59fc-4016-4682-8a72-0db524c0f388.png)
![test2](https://user-images.githubusercontent.com/34017026/156908594-0221d8ca-ad17-4330-89ed-6ad11f2fd1aa.png)

**Comment by Djpowell23** [comment]
I believe the current issue with this is when they are bought from a shop. when spawned in, they work as intended, but the uses info gets lost in shops. Still looking for a way to use that snippet in the "giveitem" command and having the item inherently have that info. maybe its a switch in items.lua or something, still looking

**Comment by tsoulii** [comment]
I know the problem lies here as in the surah, and there is something missing from the event in order to complete an action like “harness.”

![test4](https://user-images.githubusercontent.com/34017026/156915417-a83bde3a-49bc-40f1-9fea-45278dc9453e.png)

-1  doesn't know her
