### ISSUE TITLE
If you want to add the lighter, edit this on server.lua

### ISSUE THREAD

**Issue by tsoulii** [Djpowell23/gb-cigarettes#5]
Change line 11 -- Create the cigarette to 21 and put it there

--Create the cigarette
```QBCore.Functions.CreateUseableItem("cigarette", function(source, item)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if Player.Functions.GetItemByName("lighter") then
			if Player.Functions.RemoveItem(item.name, 1, item.slot) then
				TriggerClientEvent("cigarettes:client:UseCigarette", src)
			end
    else
        TriggerClientEvent("QBCore:Notify", source, "You don't have a lighter", "error")
    end
end)
```

Hope it is useful for everyone   :+1:

**Comment by Djpowell23** [comment]
so i just replace the current "create the cigarette" function with that snippet, correct?

**Comment by Djpowell23** [comment]
will test tonight or tomorrow

**Comment by tsoulii** [comment]
Change that function only and do restart gb-cigarettes
  You will be asked for a lighter

**Comment by Djpowell23** [comment]
Perfect. Thank you so much. 
Any idea about the known bug of it not having 20 uses when buying from shops? only works when spawned in

**Comment by tsoulii** [comment]
> 

I'll look into it later

**Comment by Djpowell23** [comment]
appreciate it. no worries, i figured it was worth a shot asking haha

**Comment by tsoulii** [comment]
Look at the previous comment in order to know where the defect is, just focus on completing the work and bring everything necessary
