### ISSUE TITLE
attempt to perform arithmetic on a nil value (field 'uses')

### ISSUE THREAD

**Issue by ryz87** [Djpowell23/gb-cigarettes#6]
i got this issues

[script:gb-cigarettes] SCRIPT ERROR: @gb-cigarettes/server/main.lua:32: attempt to perform arithmetic on a nil value (field 'uses')

**Comment by Djpowell23** [comment]
This should be fixed with the snippet added towards the bottom of the readme. if it isn't feel free to create another issue. I was away from technology for a couple weeks but I have returned now. Thanks!
