### ISSUE TITLE
Hey Fix for the attempt to perform arithmetic on a nil value (field 'uses') - 

### ISSUE THREAD

**Issue by STITCH42011** [Djpowell23/gb-cigarettes#7]
Hello, if the durries are spawned via /giveitem then the original code Works!
if itemData["name"] == "redwoodcigs" then
                   info.uses = 20 end
                   
but if your using your script with QB-shops u need to navigate to QBCore.Shared.SplitStr(shopType, "_")[1] == "Itemshop" in server main.lua then

in there, you will see 2 if statements stating cash balance and bank balance you need to add the lines of code under both

so 

if durries are spawned via buying from the shop then it needs to be
if itemData["name"] == "redwoodcigs" then
                    itemData.info.uses = 20 end

so for example your code should look like this \/\/
https://gyazo.com/cc850c11ed7a768f6c3bd195dc4d18a1

**Comment by Djpowell23** [comment]
That is very good to know. I solved the issue with them by putting an extra part in the config of qb-shops, but this snippet you directed me towards if very helpful for future use. Cheers!
