### ISSUE TITLE
Fixing the Nil issue

### ISSUE THREAD

**Issue by frigg007** [Djpowell23/gb-cigarettes#8]
The Nil issue seems to come from packs of cigarettes that have been added to the store. How I was able to fix it was by adding the count to the item in the config file for the shops see my snip below. This also removes the pack once it hits 20 instead of the pack being unlimited. 
qb-shops --> Config.lua
```
        [13] = {
            name = "redwoodcigs",
            price = 200,
            amount = 5000,
            info = {
                uses = 20
            },
            type = "item",
            slot = 13,
        },
```

Hope it helps the rest of you all :D

**Comment by Djpowell23** [comment]
Apologies, I was unable to reach a computer the past couple weeks, I am testing this now and if it works I'll add it to the README. I think I tried a variation of this but likely did it incorrectly at the time. Cheers!
